### ISSUE TITLE
Program counter of memory access instruction

### ISSUE THREAD

**Issue by Hematies** [ASG-ICT/SPEC2017-Trace#1]
Greetings! First of all, I must say that I have been looking for SPEC memory traces for a while and I am grateful to finally find this GitHub project.

Going directly to the matter of this issue, I have one main doubt: is it possible to record the program counter of the instruction responsable of each memory access in the trace? If it isn't so, could that feature be implemented in a future version?

Thanks in advance!

**Comment by ASG-ICT** [comment]
HMTT can only get information on the bus. HMTT cannot get the information of the registers in the cpu, including PC.

**Comment by Hematies** [comment]
I see... Thanks for the answer!
